services:

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jebastin
    ports:
      - "5432:5432"

  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis-broker
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  app:
    image: integration-project:latest
    container_name: integration-project
    depends_on:
      - postgres
      - artemis
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: jebastin

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db

      SPRING_ARTEMIS_BROKER_URL: tcp://artemis:61616
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin